### ISSUE TITLE
bulk restore of databases inefficient 

### ISSUE THREAD

**Issue by eoyduett** [bseltz-cohesity/scripts#130] opened 2023-11-07 11:22 UTC
Hi

doing bulk restore of many databases is very inefficient.

when you restore more than 100 databases, restore should do it in batches  100 databases at a time.

restoring 1000+ db's also takes some time to complete and is putting additional load on the cluster when it has to create one task per db.

if you need to do restore of 50-290k databases incase of disaster it does not scale.

restoreSQLDBs.ps1

example of input

.\restoreSQLDBs.ps1 -sourceServer someserver -sourceInstance SQL12345 -allDBs -targetServer someserver -targetInstance SQL67891 -vip ip -username some_user -password some_password -mfaCode mfa_code -mdfFolder c:\some_folder

**Comment by bseltz-cohesity** [comment] 2023-11-07 11:29
Which script are you referring to?

**Comment by eoyduett** [comment] 2023-11-07 11:33
restoreSQLDBs.ps1

**Comment by bseltz-cohesity** [comment] 2023-11-07 12:05
Bulk database restore is a new feature in Cohesity version 6.8.x. Adding that feature to the script will require a complete rewrite. I am working with your Cohesity team to initiate the development work on the new script. Closing this issue since the current script works as designed.

**Closed by bseltz-cohesity** 2023-11-07 12:05 UTC

**Comment by eoyduett** [comment] 2023-11-07 12:08
ok, but the ui in 6.8 does not have the option to select all databases in an instance
you have to use the checkboxes and click

you should able to select the instance, and date, and all databases.

**Comment by bseltz-cohesity** [comment] 2023-11-07 12:09
Yes the new script will have those features
